services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./auth-service/internal/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/authdb?sslmode=disable
      JWT_SECRET: your-secret-key-change-in-production
      VERIFICATION_SECRET: verification-secret-change-in-production
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: ""
      FRONTEND_URL: http://localhost:3000
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      PORT: 8080
      AUTH_SERVICE_ADDR: auth-service:50051
      DATABASE_URL: postgres://user:password@postgres:5432/authdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
